### PR TITLE
Accommodate changes to recob::Hit

### PR DESCRIPTION
**Pull request by knoepfel**
Pursuant to changes introduced in https://github.com/LArSoft/lardataobj/pull/42.

### CODE REVIEW

**Comment by bear-is-asleep** [comment]
Converting to draft until the larsoft PR is merged.

**Comment by ibsafa** [comment]
@bear-is-asleep this has been merged in larsoft now

**Comment by bear-is-asleep** [comment]
trigger build LArSoft/lar*@LARSOFT_SUITE_v09_92_00 SBNSoftware/sbnanaobj@bug/coackley_ciCafv09_91_02

**Comment by bear-is-asleep** [comment]
Looks like there's still a place that needs to be updated in the CI for this change - 
```
/scratch/workspace/sbnd_ci/label_exp/swarm/label_exp2/swarm/SBND/compilation_test_sbndcode/galleryTest/source/HitAnalysisAlg.cpp:250:43: error: 'const class recob::Hit' has no member named 'SummedADC'; did you mean 'ROISummedADC'?
```

**Comment by bear-is-asleep** [comment]
trigger build LArSoft/lar*@LARSOFT_SUITE_v09_92_00 SBNSoftware/sbnanaobj@bug/coackley_ciCafv09_91_02

**Comment by bear-is-asleep** [comment]
trigger build LArSoft/lar*@LARSOFT_SUITE_v09_92_00 SBNSoftware/sbnanaobj@bug/coackley_ciCafv09_91_02

**Comment by bear-is-asleep** [comment]
trigger build LArSoft/lar*@LARSOFT_SUITE_v09_93_01 SBNSoftware/sbnanaobj@bug/coackley_ciCafv09_91_02

**Review by bear-is-asleep — APPROVED** [review]

**Comment by henrylay97** [comment]
Just noting that this ideally shouldn't have been merged yet because the object changes only make it into LArSoft v10_01_02 which we are not yet inheriting from. When further intermediate (mainly v9) releases are made we'll need to revert these changes in those branches.
